### ISSUE TITLE
Populate wiki with relevant documentation

### ISSUE THREAD

**Issue by mathuin** [TinyMultiplayerBot/TinyMultiplayerBot#1]
Now that the project has been created and the wiki is available, it's time to start writing documentation.

First step will be user stories.  Alice and Bob want to play Civilization 5 with Charlie, but hotseat isn't working for them.  Whatever will they do?  We can walk them through everything from account creation and password changes to making moves and endgame cleanup tasks once someone's finally stood the test of time.

Once we've developed user stories, we can document the API such that it facilitates those stories and does very little else.  Want another feature?  Write another story, make sure the feature fits, then update the API.

After the API wrestling is done, then we write some tests.  @brutal-chaos has already started this process, so we can move forward from there.  These are just unit tests, not integration tests.  If the tests bring up something in the API that's not right, go back to the API, make sure it fits the user stories, etc.  But that is all beyond the scope of this issue.

**Comment by mathuin** [comment]
The wiki's link is https://github.com/TinyMultiplayerBot/TinyMultiplayerBot/wiki duh

**Comment by mathuin** [comment]
I have written a crapload of user stories.  I encourage you to go through them and check them for sanity, as well as propose answers to the questions.  Once we have most of the stories done (not counting the stories pertaining to maintaining the software) we can draft the API and documentation!

**Comment by mythmon** [comment]
@mathuin I reformatted your user stories. I pulled all the questions out of the stories in to individual bulleted lists for each header. I think this will make discussion and triage better.
