### ISSUE TITLE
User Authentication (Login)

### ISSUE THREAD

**Issue by justinnoah** [TinyMultiplayerBot/TinyMultiplayerBot#2]
We should allow (and prefer) user login via Steam, but also allow a normal user/pass for the site as well since not everyone uses steam.

**Comment by mathuin** [comment]
At first, only Civ 5 will be supported.  Civ 5 is a Steam-only game, so anyone who plays Civ 5 has a Steam account.  Leveraging their OpenID at first makes perfect sense.  When other games are supported, non-Steam accounts can be implemented at that time.

**Comment by mathuin** [comment]
Also, figured out how to reference issues in wikis :-P  [#2](../issues/2)

**Comment by mythmon** [comment]
NIT: Steam doesn't use OpenID, and saying that implies a lot of other
things. Steam has an Oauth2 authentication scheme, which is different than
OpenID.

--Mike Cooper

**Comment by justinnoah** [comment]
@mythmon ctrl+f on http://steamcommunity.com/dev for OpenID

Where did you find the OAuth2 authentication information?

**Comment by justinnoah** [comment]
I think I would prefer to use OAuth2 if they have it.

**Comment by mythmon** [comment]
Oh. Weird. Well, the good news is we can just implement OpenID and then use
any provider, including Steam. No need for username and password at all.

**Comment by mathuin** [comment]
@brutal-chaos Love the new documentation!  I got an API key -- those terms and conditions will require some documentation on our part, which probably belongs as part of this issue -- but I don't know where to put it.  There's no "YOUR KEY HERE" in tmb/views.py or any other file that I can see. Help!

**Comment by justinnoah** [comment]
https://github.com/TinyMultiplayerBot/TinyMultiplayerBot/blob/jnoah/issues/2_login/tmb/views.py#L15

As for the Terms and Conditions we could note that Valve have TaCs that the user should take note of, but I don't think we need to include them.

**Comment by mathuin** [comment]
Ah, okay, I saw the notes in the branch README but hadn't switched to that branch on my checkout, dur!

http://steamcommunity.com/dev/apiterms

We're wearing two hats here.

With the dev hat on, we should definitely include a link to these terms in the documentation -- yes, people see them when they get a key but this makes it easy to go back to them for reference -- and we should keep them in mind when looking at code which interfaces with Steam data to ensure we're doing the right thing.

With the ops hat on, we must have a privacy policy for our users that matches the requirements specified in the URL above.  Whether or not that policy is included in a file that's checked into the repo is up to us -- I say yes, but I could see an argument towards having other site managers add one during the installation process as an expression of explicit compliance with the API terms.

**Comment by mathuin** [comment]
Okay, cloned the repo, checked out your branch, read the docs, built the virtualenv, set the API key, and initialized the database.

I then ran the tests, and this is what I got:

```
(TinyMultiplayerBot)jmt@nala:~/git/TinyMultiplayerBot/TinyMultiplayerBot$ python tests.py 
 * Running on http://127.0.0.1:8943/
 * Restarting with reloader
127.0.0.1 - - [24/Sep/2014 10:16:51] "GET / HTTP/1.1" 200 -
.127.0.0.1 - - [24/Sep/2014 10:16:52] "GET / HTTP/1.1" 200 -
..
----------------------------------------------------------------------
Ran 2 tests in 1.607s

OK
(TinyMultiplayerBot)jmt@nala:~/git/TinyMultiplayerBot/TinyMultiplayerBot$ E
======================================================================
ERROR: test_create_account (__main__.TestTMR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 36, in test_create_account
    u2 = User.get_or_create(steamid)
  File "/home/jmt/git/TinyMultiplayerBot/TinyMultiplayerBot/tmb/models.py", line 16, in get_or_create
    user = User.query.filter_by(steamid=steamid).first()
  File "/home/jmt/.virtualenvs/TinyMultiplayerBot/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2341, in first
    ret = list(self[0:1])
  File "/home/jmt/.virtualenvs/TinyMultiplayerBot/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2208, in __getitem__
    return list(res)
  File "/home/jmt/.virtualenvs/TinyMultiplayerBot/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
    return self._execute_and_instances(context)
  File "/home/jmt/.virtualenvs/TinyMultiplayerBot/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2427, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/jmt/.virtualenvs/TinyMultiplayerBot/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/home/jmt/.virtualenvs/TinyMultiplayerBot/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/jmt/.virtualenvs/TinyMultiplayerBot/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/jmt/.virtualenvs/TinyMultiplayerBot/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/home/jmt/.virtualenvs/TinyMultiplayerBot/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/home/jmt/.virtualenvs/TinyMultiplayerBot/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/jmt/.virtualenvs/TinyMultiplayerBot/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/home/jmt/.virtualenvs/TinyMultiplayerBot/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) no such table: users u'SELECT users.id AS users_id, users.username AS users_username, users.steamid AS users_steamid \nFROM users \nWHERE users.steamid = ?\n LIMIT ? OFFSET ?' ('au9a0ou9ea0', 1, 0)

----------------------------------------------------------------------
Ran 2 tests in 1.404s

FAILED (errors=1)
```

I'm pretty sure I wasn't supposed to see an error. ;-)  I'm also confused as to why I see my prompt before the final test has already run.  It looks sorta like a test server has to be up and running in order to run the tests (which is fine, Django does that too with https://docs.djangoproject.com/en/1.4/topics/testing/#live-test-server) but behavior's somewhat inconsistent.  Rerunning the tests gives me either pass or fail on the last test, usually with fun stuff like "no such table" as above.

**Comment by justinnoah** [comment]
I'm not sure what exactly is going on there. I get the same issue with test running output showing up after the prompt (but not always a failure!). It's something I've been looking into.

**Comment by mythmon** [comment]
I'd recommend avoiding live test server style testing. It makes things slower, harder to test, and more annoying.

**Comment by justinnoah** [comment]
That test is only a stub for future tests. I could just drop it for the time being since it doesn't server any purpose currently.
